import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'
import { AppProvider, useGlogalContext } from '@/lib/Context'
import { BookingSidebar } from '@/components/BookingSidebar/BookingSidebar'
// import BookingSidebar from '@/components/BookingSidebar'
// import { NavigationMenuDemo } from '@/components/BookingSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <AppProvider>
        <body className={inter.className}>
          <BookingSidebar />
          <Header />

          {children}
        </body>
      </AppProvider>
    </html>
  )
}
